name: spectia
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.8.30=hbcca054_0
  - ld_impl_linux-64=2.40=hf3520f5_7
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgomp=14.1.0=h77fa898_1
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.46.1=hadc24fc_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=h4ab18f5_1
  - ncurses=6.5=he02047a_1
  - openssl=3.3.1=hb9d3cd8_3
  - pip=24.2=pyh8b19718_1
  - python=3.10.14=hd12c33a_0_cpython
  - readline=8.2=h8228510_1
  - setuptools=73.0.1=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.44.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
    - altair==5.4.1
    - attrs==24.2.0
    - blinker==1.8.2
    - cachetools==5.5.0
    - certifi==2024.8.30
    - charset-normalizer==3.3.2
    - click==8.1.7
    - gitdb==4.0.11
    - gitpython==3.1.43
    - idna==3.8
    - jinja2==3.1.4
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - mdurl==0.1.2
    - narwhals==1.6.2
    - numpy==2.1.1
    - nvidia-ml-py3==7.352.0
    - packaging==24.1
    - pandas==2.2.2
    - pillow==10.4.0
    - protobuf==5.28.0
    - psutil==5.9.8
    - pyarrow==17.0.0
    - pydeck==0.9.1
    - pygments==2.18.0
    - python-dateutil==2.9.0.post0
    - pytz==2024.1
    - referencing==0.35.1
    - requests==2.32.3
    - rich==13.8.0
    - rpds-py==0.20.0
    - six==1.16.0
    - smmap==5.0.1
    - streamlit==1.37.1
    - tenacity==8.5.0
    - toml==0.10.2
    - tornado==6.4.1
    - typing-extensions==4.12.2
    - tzdata==2024.1
    - urllib3==2.2.2
    - watchdog==4.0.2
